[package]
name = "markovchain-client-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
thiserror = "2.0.17"
reqwest = "0.12.24"
serde_json = "1.0.145"
serde = { version = "1.0.228", features = ["derive"] }
